services:
  jupyter:
    image: pdeitel/pydsft:latest
    container_name: jupyter-tf-extended
    ports:
      - "8888:8888"   # Jupyter
      - "4040:4040"   # Spark UI
      - "8050:8050"   # Dash
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes